name: Deploy to Central Repo

on:
  push: {}

jobs:
  deploy:
    if: github.repository == 'centrual/pokerogue'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Put env variables in .env
        run: |
          echo "VITE_BYPASS_LOGIN=${{ vars.VITE_BYPASS_LOGIN }}" > .env
          echo "VITE_BYPASS_TUTORIAL=${{ vars.VITE_BYPASS_TUTORIAL }}" >> .env
          echo "VITE_SERVER_URL=${{ vars.VITE_SERVER_URL }}" >> .env
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          VITE_BYPASS_LOGIN: ${{ vars.VITE_BYPASS_LOGIN }}
          VITE_BYPASS_TUTORIAL: ${{ vars.VITE_BYPASS_TUTORIAL }}
          VITE_SERVER_URL: ${{ vars.VITE_SERVER_URL }}
      - name: Copy .env to dist
        run: cp .env dist/.env
      - name: Push dist directory to centrual/pokerogue
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: dist/
          destination-github-username: 'centrual'
          destination-repository-name: 'pokerogue-build'
          user-email: centrual@outlook.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main